Create 0xE4F6D46C244Bb7Cf3e218CDFB5C35cf9a4d9c920.json
ethereum-lists/tokens pull request #527
Opened 2021-05-26 16:05 UTC by projectdonkey

Add DONK token

2021-05-27 10:29 UTC, ligi requested changes
Thanks! But to merge it the address must be in [ERC-55](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-55.md) (filename and address field)

It actually seems good in the filename - but for sure not in the field.

You can create addresses with checksum e.g. with this tool: https://ethsum.netlify.app/

2021-06-11 02:06 UTC, projectdonkey commented
Hi 

The requested changed has been completed thanks

2021-06-27 20:51 UTC, ligi commented on tokens/eth/0xE4F6D46C244Bb7Cf3e218CDFB5C35cf9a4d9c920.json
> +  "address": "0xE4F6D46C244Bb7Cf3e218CDFB5C35cf9a4d9c920.json",
```suggestion
  "address": "0xE4F6D46C244Bb7Cf3e218CDFB5C35cf9a4d9c920",
```

2021-06-27 20:53 UTC, ligi approved these changes

2021-06-27 20:53 UTC, merged

2021-06-28 00:03 UTC, projectdonkey commented
Please list Donkey